# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<SCRIPT
sudo apt-get install python-dev
sudo easy_install pip
sudo pip install virutalenvwrapper
sudo apt-get install libffi-dev
sudo apt-get install libgit2-dev
SCRIPT
#manual
# setup virtualenvwrapper
# activate virual env
# pip install salt
# pip install GitPython

# sudo apt-get install salt-minion python-pygit2 -y

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/wily64"
  config.vm.provision "shell", inline: $script
end
